# Generated by Django 2.1.7 on 2021-01-23 18:20

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_broadcast_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast_email',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
